### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by danik-ik** [neochief/birman-typography-layouts-for-ubuntu#5]
Вы можете упомянуть в описании, что в 20.04 (последняя LTS версия на сегодня) тоже работает. У меня KUBUNTU 20.04, установилось без проблем по инструкции к 18.04, работает прекрасно

**Comment by online** [comment]
@danik-ik так вообще на Ubuntu / Manjaro (GNOME) можно нативно решать эту задачу через `gnome-tweak-tool`.

После установки переходите в:

Дополнительные настройки GNOME → Дополнительные параметры раскладки → Клавиша для выбора 3-го уровня → Правая `Alt`; `Shift` + права `Alt` работают как Compose.

Разные параметры совместимости → Включить дополнительные типографские символы

И на этом всё. Плюс в том, что ввод типографских символов будет работать на всех раскладках. Проверял как минимум на: UA, RU, EN.

**Comment by danik-ik** [comment]
У мну КДЕ. Настройки все нашёл и попробовал, но увы, "что-то здесь не так".
А разбираться при наличии готового надёжного решения большого желания нет

ср, 3 мар. 2021 г., 15:06 Sergey <notifications@github.com>:

**Comment by online** [comment]
@danik-ik в KDE точно есть такие же настройки. Но вы уже сами решайте, как вам удобнее. 

Лично мне нативные решения в разы лучше. К тому же нет нужды переживать о том, что при обновлении до новой версии ОС стороннее решение перестанет работать.

**Comment by neochief** [comment]
@danik-ik , cпасибо вам, описание обновил.
